### ISSUE TITLE
Keyboard auto opens on script startup

### ISSUE THREAD

**Issue by avielsh** [gilleswaeber/emoji-keyboard#12]
Hi ,
Great script, stumbled across after moving to win 10 , disabling windows 10 shortcuts and trying to open the emoji keyboard via autohotkey
One issue I encoutnred 
Script opens keyboard on start - bad if adding to windows startup -  I think there's a return missing at the end of the  autorun area
adding ```return``` on line 102, fixes this issue.

Cheers

**Comment by gilleswaeber** [comment]
Hi, there was indeed a missing `return`.
I fixed it in b982152
