### ISSUE TITLE
Feature: Auto reposition under active application in multi monitor setup

### ISSUE THREAD

**Issue by avielsh** [gilleswaeber/emoji-keyboard#13]
Hi,
In A multi-monitor setup it would be useful if the keyboard would open under the currently active app.
( Usability feature )

**Comment by gilleswaeber** [comment]
That took a while... fixed in [f1fe9ac](https://github.com/gilleswaeber/emoji-keyboard/commit/f1fe9ace5170129950704ca93f46c6da394c9e67)
