### ISSUE TITLE
Recently used list

### ISSUE THREAD

**Issue by robertwidfen** [gilleswaeber/emoji-keyboard#14]
Being really annoyed by the new emoji panel of Windows 11, I was searching for alternatives.

Emoji-keyboard is really nice and so fast to use just buy keys, but I miss a recently used list. 😇

**Comment by gilleswaeber** [comment]
Thanks 😉
I can confirm this is one of the next features to come, after the Unicode update and some other improvements, but I can't tell exactly when yet.

**Comment by robertwidfen** [comment]
Hi Gilles,

hey that is good to hear 😀 - I must admit, that I was so triggered and did
like the whole look and feel so much that I cloned the repo and started
hacking 😉 ...  see the attached animated GIF ... thanks for the great
work, I just accidently found it when taking AHK into account to
automatically switch to "recent" in the sucking Wín11 integrated emoji
panel.

So far I did not push the repo to github - I just registered
yesterday 😇 and want to test a bit more ...

Am Mi., 1. März 2023 um 12:35 Uhr schrieb Gilles Waeber <
***@***.***>:

**Comment by gilleswaeber** [comment]
Hi Robert, it seems the gif didn't go through

**Comment by robertwidfen** [comment]
Hmm, that was by email, let's see if it works by browser ... 🤔

![emoji-keyboard-recent](https://user-images.githubusercontent.com/126524724/222363298-a3b4f9d6-6a36-4619-89de-4a6034ff24e5.gif)

**Comment by gilleswaeber** [comment]
It worked, nice gif 😎

**Comment by gilleswaeber** [comment]
Added with #16, thanks
