### ISSUE TITLE
Release is incorrect

### ISSUE THREAD

**Issue by anzz1** [gilleswaeber/emoji-keyboard#19]
Since the [WebView2Loader.dll](https://github.com/gilleswaeber/emoji-keyboard/blob/master/lib/thqby/WebView2/64bit/WebView2Loader.dll) files are configured to use Git LFS, the repo must be retrieved with `git clone` to get the correct libraries instead of just text files pointing to the LFS. 

The [release v1.4](https://github.com/gilleswaeber/emoji-keyboard/archive/refs/tags/v1.4.zip) contains those DLLs as text files which obviously doesn't work.

Also if you use the "Download ZIP" function, it also doesn't work because of LFS. This probably would be good to mention in the Readme.
![image](https://github.com/gilleswaeber/emoji-keyboard/assets/13628128/943defd0-14b5-424d-9e86-f6b3b3f7f829)

**Comment by gilleswaeber** [comment]
Thank you for reporting this. It also applies to the emoji font files.

I added a zip to the 1.4 release and made a new release since it's been a while (and Noto still haven't been updated to 15.1).
I also added a link to download them in the description.

**Comment by anzz1** [comment]
Thanks !

One more thing, is it possible to add config option to always use fallback icons?

Then it would work in Windows 7, where currently it looks like this:

![image](https://github.com/gilleswaeber/emoji-keyboard/assets/13628128/e3ae85a1-d3d7-45c7-a627-ec504ed0b257)

**Comment by gilleswaeber** [comment]
Hi, there are integrated [fallback rules](https://github.com/gilleswaeber/emoji-keyboard/blob/master/wwwassets/script/config/fallback.ts) that are supposed to apply depending on the OS version, but it seems that some update broke that. I'll have a look at it

**Comment by gilleswaeber** [comment]
Hi,this should be fixed now. I don't have any Windows 7 device atm, but I tested it on Windows 8.1 🐱‍💻

**Comment by anzz1** [comment]
Works 😇😇

![image](https://github.com/gilleswaeber/emoji-keyboard/assets/13628128/915469ea-3723-41df-a6f9-02566b7141a4)
