### ISSUE TITLE
OSD.ahk, unknown aria-owns...

### ISSUE THREAD

**Issue by mslonik** [gilleswaeber/emoji-keyboard#9]
Hi, I get the following error:

"C:\Program Files\AutoHotkey\AutoHotkey.exe" /ErrorStdOut "C:\AHK\Emoji\assets\OSD.ahk"    
C:\AHK\Emoji\assets\OSD.ahk (141) : ==> This line does not contain a recognized action.
     Specifically: aria-owns="jump-to-results"

My system is Windows 10. I have to idea how to deal with it. Any help is appreciated.

**Comment by mslonik** [comment]
My mistake, sorry. After full pull of all files from repository, not just an App.ahk, everything is fine. Great application.

**Comment by gilleswaeber** [comment]
Thanks for giving it a try. That should maybe made more clear.
I just published a new version that includes some changes I was working on regarding the search function and an update of the emoji db.
